# Generated by Django 6.0.6 on 2026-06-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], max_length=10)),
                ('paper_set', models.CharField(choices=[('SET_A', 'Set A'), ('SET_B', 'Set B')], max_length=5)),
                ('answers', models.JSONField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('group', 'paper_set')},
            },
        ),
    ]
