# Generated by Django 6.0.6 on 2026-06-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('group', models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], max_length=10)),
                ('paper_set', models.CharField(choices=[('SET_A', 'Set A'), ('SET_B', 'Set B')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schools.school')),
            ],
        ),
    ]
