# Generated by Django 6.0.6 on 2026-07-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='full_name',
        ),
    ]
