# Generated by Django 6.0.6 on 2026-07-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_remove_participant_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('roll_number', 'group')},
        ),
    ]
