# Generated by Django 6.0.6 on 2026-06-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer_keys', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OMRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='omr_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EVALUATED', 'Evaluated'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('detected_answers', models.JSONField(blank=True, null=True)),
                ('answer_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='answer_keys.answerkey')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='omr_submission', to='participants.participant')),
            ],
        ),
    ]
