# Generated by Django 6.0.5 on 2026-07-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_omrsubmission_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrsubmission',
            name='evaluator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='omrsubmission',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
